name: useful_in_the_kitchen
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  property_change_notifier: ^0.3.0
  provider: ^6.0.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  http: ^0.13.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true